"use client";
import { useState } from "react";
import { motion } from "motion/react";
import type {
  ColorPalette,
  TypePairing,
  Persona,
  MediaChannel,
} from "@/lib/types";

type Props = {
  kind: "brand" | "campaign";
  name: string;
  archetypeLabel: string;
  toneLabel: string;
  palette: ColorPalette;
  type: TypePairing;
  persona: Persona;
  tagline?: string;
  story?: string;
  description?: string;
  mockupImages: (string | undefined)[];
  mockupPrompts: string[];
  /** Kept for backwards compatibility; pattern visualization removed from bento. */
  patternIdea?: string;
  headlines?: string[];
  cta?: string;
  channelIdeas?: Partial<Record<MediaChannel, string>>;
  logoDataUrl?: string;
  /** Optional concept thumbnails from step 6 — used in the moodboard strip */
  conceptThumbnails?: (string | undefined)[];
  /** Called when user clicks regenerate on a mockup tile */
  onRegenMockup?: (idx: number) => Promise<void>;
};

/**
 * The complete brand-book bento — a designed, editorial composition of every
 * brand-system primitive (logo, color, type, persona) followed by an applied-
 * design gallery of 8 categorized surface mockups generated by Nano Banana 2.
 *
 * Layout rhythm:
 *   ROW 1 — establish:    HERO LOCKUP · ESSENCE
 *   ROW 2 — logo system:  4 lockup variants spanning full width
 *   ROW 3 — system specs: COLOR · TYPOGRAPHY · PERSONA
 *   ROW 4 — applied hero: HERO MOCKUP · SECONDARY VERTICAL · 2 SQUARE STACK
 *   ROW 5 — applied wide: OOH · COLLATERAL/POSTER
 *   ROW 6 — applied new:  EDITORIAL/DIGITAL BANNER · ENVIRONMENT/ACTIVATION
 *   ROW 7 — campaign only: HEADLINES · CTA · CHANNELS
 *   ROW 8 — close:        DETAILS BAR
 *
 * Built defensively: every field access uses optional chaining + safe fallbacks
 * so a malformed AI response can never crash the page.
 */
export default function Bento(props: Props) {
  const {
    kind,
    name,
    archetypeLabel,
    toneLabel,
    palette,
    type,
    persona,
    tagline,
    story,
    description,
    mockupImages,
    headlines,
    cta,
    channelIdeas,
    logoDataUrl,
    onRegenMockup,
  } = props;

  const [regenIdx, setRegenIdx] = useState<number | null>(null);
  const handleRegen = async (i: number) => {
    if (!onRegenMockup) return;
    setRegenIdx(i);
    try {
      await onRegenMockup(i);
    } finally {
      setRegenIdx(null);
    }
  };

  // ---------- Safe palette / persona / type defaults ----------
  const hexes = palette?.hexes ?? [];
  const [c0, c1, c2, c3] = [
    hexes[0] || "#0a0a0a",
    hexes[1] || "#c8ff3e",
    hexes[2] || "#f5f0e8",
    hexes[3] || "#ff3e8e",
  ];
  const personaName = persona?.name ?? "—";
  const personaDescription = persona?.description ?? "";
  const personaTraits = Array.isArray(persona?.traits) ? persona!.traits : [];
  const displayFont = type?.display ?? "serif";
  const bodyFont = type?.body ?? "sans-serif";

  // Up to 4 brand principles, derived from the tone keywords.
  const toneList = (toneLabel || "").split(/,\s*/).filter(Boolean);
  const defaults = ["considered", "deliberate", "honest", "specific"];
  const principles: { word: string; descriptor: string; tint: string }[] = [
    { word: toneList[0] ?? defaults[0], descriptor: "How we move.", tint: c1 },
    { word: toneList[1] ?? defaults[1], descriptor: "How we think.", tint: c3 },
    { word: toneList[2] ?? defaults[2], descriptor: "How we speak.", tint: "#1fc9d7" },
    { word: toneList[3] ?? defaults[3], descriptor: "How we ship.", tint: c2 },
  ];

  const tileMotion = (i: number) => ({
    initial: { opacity: 0, y: 18, scale: 0.985 },
    animate: { opacity: 1, y: 0, scale: 1 },
    transition: {
      duration: 0.6,
      delay: 0.04 + i * 0.04,
      ease: [0.16, 1, 0.3, 1] as [number, number, number, number],
    },
  });

  const gfDisplay = displayFont.replace(/\s+/g, "+");
  const gfBody = bodyFont.replace(/\s+/g, "+");

  // ---------- Slot map for applied-design gallery (8 surfaces) ----------
  // Both kinds have 8 slots arranged into the same 6-tile layout, but the
  // surface category each slot represents differs per kind.
  const slotMap = (() => {
    if (kind === "campaign") {
      return {
        hero: { idx: 0, label: "hero · campaign film still" },
        verticalSecondary: { idx: 2, label: "vertical · story / reel" },
        squareTop: { idx: 1, label: "social · feed post" },
        squareBottom: { idx: 4, label: "photography · moodboard" },
        wide: { idx: 5, label: "ooh · billboard in situ" },
        midPortrait: { idx: 3, label: "campaign poster" },
        banner: { idx: 6, label: "digital banner · web marquee" },
        environment: { idx: 7, label: "activation · branded experience" },
      };
    }
    return {
      hero: { idx: 0, label: "hero · product application" },
      verticalSecondary: { idx: 2, label: "print · poster" },
      squareTop: { idx: 1, label: "social · feed post" },
      squareBottom: { idx: 5, label: "photography · brand direction" },
      wide: { idx: 3, label: "ooh · billboard in situ" },
      midPortrait: { idx: 4, label: "brand collateral · print" },
      banner: { idx: 6, label: "editorial banner · web marquee" },
      environment: { idx: 7, label: "brand environment · retail space" },
    };
  })();

  return (
    <>
      {/* Pull in the brand's actual display + body fonts so the type
          specimen renders in the chosen typography. */}
      <link
        rel="stylesheet"
        href={`https://fonts.googleapis.com/css2?family=${gfDisplay}:wght@400;500;700&family=${gfBody}:wght@400;500;600&display=swap`}
      />

      <div
        className="grid gap-3"
        style={{
          gridTemplateColumns: "repeat(12, 1fr)",
          gridAutoRows: "minmax(120px, auto)",
          gridAutoFlow: "dense",
        }}
      >
        {/* ============ 01 / HERO LOCKUP ============ */}
        <motion.div
          {...tileMotion(0)}
          className="rounded-lg p-8 md:p-10 flex flex-col justify-between relative overflow-hidden"
          style={{
            background: c0,
            color: c2,
            gridColumn: "span 8",
            gridRow: "span 3",
            minHeight: "420px",
          }}
        >
          {/* Subtle dot pattern as ambient background — NOT the brand pattern */}
          <svg
            aria-hidden
            className="absolute inset-0 w-full h-full opacity-[0.06] pointer-events-none"
            preserveAspectRatio="xMidYMid slice"
          >
            <defs>
              <pattern id="heroDots" x="0" y="0" width="36" height="36" patternUnits="userSpaceOnUse">
                <circle cx="18" cy="18" r="1" fill={c1} />
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#heroDots)" />
          </svg>

          <div className="relative z-10 flex items-start justify-between">
            <p className="font-mono text-[10px] tracking-[0.22em] uppercase" style={{ color: c2, opacity: 0.55 }}>
              {kind} system · v0.1
            </p>
            <div className="flex items-center gap-3">
              {kind === "campaign" && logoDataUrl && (
                <div className="flex items-center gap-2">
                  <span className="font-mono text-[9px] tracking-[0.22em] uppercase" style={{ color: c2, opacity: 0.5 }}>
                    for
                  </span>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={logoDataUrl} alt="Parent brand" className="h-7 w-auto object-contain" style={{ maxWidth: 80 }} />
                </div>
              )}
              <span className="font-mono text-[10px] tracking-[0.22em] uppercase" style={{ color: c1 }}>
                ● ready
              </span>
            </div>
          </div>

          <div className="relative z-10 flex items-baseline gap-5 md:gap-7">
            {kind === "brand" && logoDataUrl && (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={logoDataUrl}
                alt={`${name} logo`}
                className="h-16 md:h-24 w-auto object-contain shrink-0"
                style={{ maxWidth: 120 }}
              />
            )}
            <h2
              className="text-6xl md:text-8xl tracking-tightest leading-none"
              style={{
                fontFamily: `'${displayFont}', serif`,
                color: c2,
                fontWeight: kind === "campaign" ? 700 : 400,
                letterSpacing: kind === "campaign" ? "-0.02em" : undefined,
              }}
            >
              {name}
              <span style={{ color: c1 }}>.</span>
            </h2>
          </div>

          <div className="relative z-10 max-w-2xl">
            {tagline && (
              <p
                className="text-xl md:text-2xl mb-3 leading-snug"
                style={{ fontFamily: `'${displayFont}', serif`, fontStyle: "italic", color: c2 }}
              >
                {tagline}
              </p>
            )}
            {(description || story) && (
              <p
                className="text-sm md:text-base leading-relaxed opacity-80 max-w-xl"
                style={{ fontFamily: `'${bodyFont}', sans-serif`, color: c2 }}
              >
                {(description || story || "").slice(0, 180)}
                {(description || story || "").length > 180 && "…"}
              </p>
            )}
          </div>
        </motion.div>

        {/* ============ 02 / BRAND ESSENCE ============ */}
        <motion.div
          {...tileMotion(1)}
          className="rounded-lg p-6 md:p-7 flex flex-col"
          style={{
            background: "#0d0d0e",
            border: "1px solid #1f2128",
            gridColumn: "span 4",
            gridRow: "span 3",
            minHeight: "420px",
          }}
        >
          <p className="eyebrow mb-5">02 / {kind === "campaign" ? "campaign essence" : "brand essence"}</p>
          <div className="flex-1 space-y-5">
            {principles.map((p, i) => (
              <div key={i} className="flex items-start gap-4">
                <div
                  className="shrink-0 w-9 h-9 rounded flex items-center justify-center"
                  style={{ background: `${p.tint}15`, border: `1px solid ${p.tint}40` }}
                >
                  <PrincipleIcon idx={i} color={p.tint} />
                </div>
                <div className="flex-1 min-w-0">
                  <p
                    className="text-bone text-base font-medium capitalize leading-tight"
                    style={{ fontFamily: `'${bodyFont}', sans-serif` }}
                  >
                    {p.word}.
                  </p>
                  <p className="text-ash text-xs leading-snug mt-0.5">{p.descriptor}</p>
                </div>
              </div>
            ))}
          </div>
          <div className="mt-6 pt-4 border-t border-steel">
            <p className="font-mono text-[9px] tracking-[0.22em] uppercase text-ash">
              Principles · operating tone
            </p>
          </div>
        </motion.div>

        {/* ============ 03 / LOGO SYSTEM ============ */}
        <motion.div
          {...tileMotion(2)}
          className="rounded-lg p-6 md:p-7"
          style={{
            background: "#0d0d0e",
            border: "1px solid #1f2128",
            gridColumn: "span 12",
            gridRow: "span 1",
            minHeight: "220px",
          }}
        >
          <div className="flex items-baseline justify-between mb-4">
            <p className="eyebrow">
              03 / {kind === "campaign" ? "wordmark system · 4 lockup variants" : "logo system · 4 lockup variants"}
            </p>
            <p className="font-mono text-[10px] tracking-widest uppercase text-ash">
              {kind === "campaign" ? "campaign typography lockup" : "clear space = 1× cap-height of mark"}
            </p>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 h-[140px]">
            {kind === "campaign" || !logoDataUrl ? (
              <>
                <WordmarkVariant background={c0} textColor={c2} accent={c1} text={name} font={displayFont} label="primary · dark" />
                <WordmarkVariant background={c2} textColor={c0} accent={c3} text={name} font={displayFont} label="inverted · light" />
                <WordmarkVariant background={c1} textColor={c0} accent={c0} text={name} font={displayFont} label="accent" />
                <WordmarkVariant background="transparent" textColor={c2} accent={c2} text={name} font={displayFont} label="monochrome" outline />
              </>
            ) : (
              <>
                <LogoVariant background={c0} accent={c1} logo={logoDataUrl} label="primary · dark" />
                <LogoVariant background={c2} accent={c0} logo={logoDataUrl} label="inverted · light" />
                <LogoVariant background={c1} accent={c0} logo={logoDataUrl} label="accent" textColor={c0} />
                <LogoVariant background="transparent" accent={c2} logo={logoDataUrl} label="monochrome" outline />
              </>
            )}
          </div>
        </motion.div>

        {/* ============ 04 / COLOR SYSTEM ============ */}
        <motion.div
          {...tileMotion(3)}
          className="rounded-lg overflow-hidden flex flex-col"
          style={{
            background: "#0d0d0e",
            border: "1px solid #1f2128",
            gridColumn: "span 4",
            gridRow: "span 2",
            minHeight: "300px",
          }}
        >
          <div className="p-6 pb-3">
            <p className="eyebrow">04 / color system</p>
            <p className="text-bone text-lg leading-tight mt-1" style={{ fontFamily: `'${displayFont}', serif` }}>
              {palette?.name ?? "—"}
            </p>
            {palette?.rationale && (
              <p className="text-ash text-xs leading-relaxed mt-1.5 line-clamp-2">{palette.rationale}</p>
            )}
          </div>
          <div className="flex-1 grid grid-cols-2 grid-rows-2 min-h-[160px]">
            <ColorCell hex={c0} role="base" />
            <ColorCell hex={c1} role="accent" />
            <ColorCell hex={c2} role="surface" />
            <ColorCell hex={c3} role="pop" />
          </div>
        </motion.div>

        {/* ============ 05 / TYPOGRAPHY SPECIMEN ============ */}
        <motion.div
          {...tileMotion(4)}
          className="rounded-lg p-6 flex flex-col"
          style={{
            background: "#0d0d0e",
            border: "1px solid #1f2128",
            gridColumn: "span 4",
            gridRow: "span 2",
            minHeight: "300px",
          }}
        >
          <p className="eyebrow mb-4">05 / typography</p>
          <div className="flex items-start gap-6 mb-4">
            <p
              className="text-[88px] leading-none tracking-tightest text-bone"
              style={{ fontFamily: `'${displayFont}', serif` }}
            >
              Aa
            </p>
            <div className="flex-1 pt-2">
              <p
                className="text-bone text-xl leading-tight mb-1"
                style={{ fontFamily: `'${displayFont}', serif` }}
              >
                {displayFont}
              </p>
              <p className="text-ash text-xs leading-relaxed" style={{ fontFamily: `'${bodyFont}', sans-serif` }}>
                Display · headlines, titles, marquee moments.
              </p>
              <div className="mt-4 pt-3 border-t border-steel">
                <p
                  className="text-bone text-base leading-tight"
                  style={{ fontFamily: `'${bodyFont}', sans-serif`, fontWeight: 500 }}
                >
                  {bodyFont}
                </p>
                <p
                  className="text-ash text-xs leading-relaxed mt-0.5"
                  style={{ fontFamily: `'${bodyFont}', sans-serif` }}
                >
                  Body · paragraphs, UI, captions.
                </p>
              </div>
            </div>
          </div>
          <div className="mt-auto pt-3 border-t border-steel">
            <p
              className="text-ash text-[11px] leading-relaxed tracking-tight"
              style={{ fontFamily: `'${bodyFont}', sans-serif` }}
            >
              ABCDEFGHIJKLMNOPQRSTUVWXYZ
              <br />
              abcdefghijklmnopqrstuvwxyz
              <br />
              0123456789 !?@#$%&*()
            </p>
          </div>
        </motion.div>

        {/* ============ 06 / PERSONA ============ */}
        <motion.div
          {...tileMotion(5)}
          className="rounded-lg p-6 flex flex-col border"
          style={{
            background: "#0d0d0e",
            borderColor: c1,
            gridColumn: "span 4",
            gridRow: "span 2",
            minHeight: "300px",
          }}
        >
          <div className="flex items-baseline justify-between mb-3">
            <p className="eyebrow">06 / persona</p>
            <p className="font-mono text-[10px] tracking-widest uppercase text-ash truncate ml-2">
              {archetypeLabel}
            </p>
          </div>
          <p
            className="text-4xl md:text-5xl leading-none tracking-tightest mb-3"
            style={{ fontFamily: `'${displayFont}', serif`, color: c2 }}
          >
            {personaName}
          </p>
          <p
            className="text-sm leading-relaxed flex-1 text-ash overflow-hidden"
            style={{
              fontFamily: `'${bodyFont}', sans-serif`,
              display: "-webkit-box",
              WebkitLineClamp: 5,
              WebkitBoxOrient: "vertical",
            }}
          >
            {personaDescription}
          </p>
          <div className="flex flex-wrap gap-1.5 mt-4">
            {personaTraits.slice(0, 6).map((t) => (
              <span
                key={t}
                className="font-mono text-[10px] uppercase tracking-widest px-2.5 py-1 rounded"
                style={{ background: `${c1}1a`, color: c1, border: `1px solid ${c1}40` }}
              >
                {t}
              </span>
            ))}
          </div>
        </motion.div>

        {/* ============ 07 / HERO APPLICATION (slot 0, 9:16) ============ */}
        <motion.div
          {...tileMotion(6)}
          className="rounded-lg overflow-hidden relative group"
          style={{
            gridColumn: "span 5",
            gridRow: "span 4",
            background: c3,
            minHeight: "640px",
          }}
        >
          <MockupTile
            image={mockupImages[slotMap.hero.idx]}
            regenerating={regenIdx === slotMap.hero.idx}
            onRegen={onRegenMockup ? () => handleRegen(slotMap.hero.idx) : undefined}
          />
          <div className="absolute inset-0 flex flex-col justify-between p-5 pointer-events-none">
            <p
              className="font-mono text-[10px] tracking-[0.22em] uppercase mix-blend-difference"
              style={{ color: c2 }}
            >
              07 / {slotMap.hero.label}
            </p>
            <div className="max-w-[85%]">
              <p
                className="text-3xl md:text-4xl leading-none mix-blend-difference"
                style={{ fontFamily: `'${displayFont}', serif`, color: c2 }}
              >
                {headlines?.[0] ?? tagline ?? "Made with intent."}
              </p>
            </div>
          </div>
        </motion.div>

        {/* ============ 08 / SECONDARY VERTICAL (poster brand / story-reel campaign) ============ */}
        <motion.div
          {...tileMotion(7)}
          className="rounded-lg overflow-hidden relative group"
          style={{
            gridColumn: "span 4",
            gridRow: "span 4",
            background: c2,
            minHeight: "640px",
          }}
        >
          <MockupTile
            image={mockupImages[slotMap.verticalSecondary.idx]}
            regenerating={regenIdx === slotMap.verticalSecondary.idx}
            onRegen={onRegenMockup ? () => handleRegen(slotMap.verticalSecondary.idx) : undefined}
          />
          <p
            className="absolute top-4 left-4 font-mono text-[10px] tracking-[0.22em] uppercase mix-blend-difference pointer-events-none"
            style={{ color: c2 }}
          >
            08 / {slotMap.verticalSecondary.label}
          </p>
        </motion.div>

        {/* ============ 09 / SOCIAL SQUARE (top right) ============ */}
        <motion.div
          {...tileMotion(8)}
          className="rounded-lg overflow-hidden relative group"
          style={{
            gridColumn: "span 3",
            gridRow: "span 2",
            background: "#1a1f28",
            minHeight: "300px",
          }}
        >
          <MockupTile
            image={mockupImages[slotMap.squareTop.idx]}
            regenerating={regenIdx === slotMap.squareTop.idx}
            onRegen={onRegenMockup ? () => handleRegen(slotMap.squareTop.idx) : undefined}
          />
          <p
            className="absolute top-4 left-4 font-mono text-[10px] tracking-[0.22em] uppercase mix-blend-difference pointer-events-none"
            style={{ color: c2 }}
          >
            09 / {slotMap.squareTop.label}
          </p>
        </motion.div>

        {/* ============ 10 / PHOTO/MOOD SQUARE (bottom right) ============ */}
        <motion.div
          {...tileMotion(9)}
          className="rounded-lg overflow-hidden relative group"
          style={{
            gridColumn: "span 3",
            gridRow: "span 2",
            background: "#0d0d0e",
            minHeight: "300px",
          }}
        >
          <MockupTile
            image={mockupImages[slotMap.squareBottom.idx]}
            regenerating={regenIdx === slotMap.squareBottom.idx}
            onRegen={onRegenMockup ? () => handleRegen(slotMap.squareBottom.idx) : undefined}
          />
          <p
            className="absolute top-4 left-4 font-mono text-[10px] tracking-[0.22em] uppercase mix-blend-difference pointer-events-none"
            style={{ color: c2 }}
          >
            10 / {slotMap.squareBottom.label}
          </p>
        </motion.div>

        {/* ============ 11 / OOH WIDE (16:9) ============ */}
        <motion.div
          {...tileMotion(10)}
          className="rounded-lg overflow-hidden relative group"
          style={{
            gridColumn: "span 8",
            gridRow: "span 2",
            background: c1,
            minHeight: "320px",
          }}
        >
          <MockupTile
            image={mockupImages[slotMap.wide.idx]}
            regenerating={regenIdx === slotMap.wide.idx}
            onRegen={onRegenMockup ? () => handleRegen(slotMap.wide.idx) : undefined}
          />
          <p
            className="absolute top-4 left-4 font-mono text-[10px] tracking-[0.22em] uppercase mix-blend-difference pointer-events-none"
            style={{ color: c0 }}
          >
            11 / {slotMap.wide.label}
          </p>
        </motion.div>

        {/* ============ 12 / COLLATERAL OR POSTER MID ============ */}
        <motion.div
          {...tileMotion(11)}
          className="rounded-lg overflow-hidden relative group"
          style={{
            gridColumn: "span 4",
            gridRow: "span 2",
            background: "#1a1f28",
            minHeight: "320px",
          }}
        >
          <MockupTile
            image={mockupImages[slotMap.midPortrait.idx]}
            regenerating={regenIdx === slotMap.midPortrait.idx}
            onRegen={onRegenMockup ? () => handleRegen(slotMap.midPortrait.idx) : undefined}
          />
          <p
            className="absolute top-4 left-4 font-mono text-[10px] tracking-[0.22em] uppercase mix-blend-difference pointer-events-none"
            style={{ color: c2 }}
          >
            12 / {slotMap.midPortrait.label}
          </p>
        </motion.div>

        {/* ============ 13 / EDITORIAL/DIGITAL BANNER WIDE (16:9 — NEW) ============ */}
        <motion.div
          {...tileMotion(12)}
          className="rounded-lg overflow-hidden relative group"
          style={{
            gridColumn: "span 8",
            gridRow: "span 2",
            background: c0,
            minHeight: "320px",
          }}
        >
          <MockupTile
            image={mockupImages[slotMap.banner.idx]}
            regenerating={regenIdx === slotMap.banner.idx}
            onRegen={onRegenMockup ? () => handleRegen(slotMap.banner.idx) : undefined}
          />
          <p
            className="absolute top-4 left-4 font-mono text-[10px] tracking-[0.22em] uppercase mix-blend-difference pointer-events-none"
            style={{ color: c2 }}
          >
            13 / {slotMap.banner.label}
          </p>
          {/* Tiny meta line bottom-right for editorial polish */}
          <p
            className="absolute bottom-4 right-4 font-mono text-[9px] tracking-[0.22em] uppercase mix-blend-difference pointer-events-none"
            style={{ color: c2, opacity: 0.7 }}
          >
            wide · 16:9
          </p>
        </motion.div>

        {/* ============ 14 / ENVIRONMENT / ACTIVATION (1:1 — NEW) ============ */}
        <motion.div
          {...tileMotion(13)}
          className="rounded-lg overflow-hidden relative group"
          style={{
            gridColumn: "span 4",
            gridRow: "span 2",
            background: c3,
            minHeight: "320px",
          }}
        >
          <MockupTile
            image={mockupImages[slotMap.environment.idx]}
            regenerating={regenIdx === slotMap.environment.idx}
            onRegen={onRegenMockup ? () => handleRegen(slotMap.environment.idx) : undefined}
          />
          <p
            className="absolute top-4 left-4 font-mono text-[10px] tracking-[0.22em] uppercase mix-blend-difference pointer-events-none"
            style={{ color: c2 }}
          >
            14 / {slotMap.environment.label}
          </p>
        </motion.div>

        {/* ============ 15 / HEADLINES (campaign only) ============ */}
        {headlines && headlines.length > 0 && (
          <motion.div
            {...tileMotion(14)}
            className="rounded-lg p-6"
            style={{
              background: c1,
              color: contrast(c1),
              gridColumn: "span 8",
              gridRow: "span 2",
              minHeight: "280px",
            }}
          >
            <p
              className="font-mono text-[10px] tracking-[0.22em] uppercase mb-4 opacity-70"
              style={{ color: contrast(c1) }}
            >
              15 / messaging · headlines
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3" style={{ fontFamily: `'${displayFont}', serif` }}>
              {headlines.slice(0, 4).map((h, i) => (
                <p key={i} className="text-xl md:text-2xl leading-tight" style={{ color: contrast(c1) }}>
                  <span className="opacity-50 mr-2 text-base">{String(i + 1).padStart(2, "0")}</span>
                  {h}
                </p>
              ))}
            </div>
          </motion.div>
        )}

        {/* ============ 16 / CTA (campaign only) ============ */}
        {cta && (
          <motion.div
            {...tileMotion(15)}
            className="rounded-lg p-6 flex flex-col justify-between"
            style={{
              background: c3,
              color: contrast(c3),
              gridColumn: "span 4",
              gridRow: "span 2",
              minHeight: "280px",
            }}
          >
            <p
              className="font-mono text-[10px] tracking-[0.22em] uppercase opacity-70"
              style={{ color: contrast(c3) }}
            >
              16 / call to action
            </p>
            <p
              className="text-3xl md:text-4xl tracking-tightest leading-none"
              style={{ fontFamily: `'${displayFont}', serif`, color: contrast(c3) }}
            >
              {cta}
            </p>
            <p
              className="font-mono text-[10px] tracking-[0.22em] uppercase opacity-50"
              style={{ color: contrast(c3) }}
            >
              primary cta · use on accent
            </p>
          </motion.div>
        )}

        {/* ============ 17 / CHANNELS (campaign only) ============ */}
        {channelIdeas &&
          Object.entries(channelIdeas).filter(([, v]) => v && v.length > 0).length > 0 && (
            <motion.div
              {...tileMotion(16)}
              className="rounded-lg p-6"
              style={{
                background: "#0d0d0e",
                border: "1px solid #1f2128",
                gridColumn: "span 12",
                gridRow: "span 2",
                minHeight: "240px",
              }}
            >
              <p className="eyebrow mb-5">17 / channels · activation ideas</p>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-4">
                {Object.entries(channelIdeas)
                  .filter(([, v]) => v && v.length > 0)
                  .slice(0, 6)
                  .map(([ch, idea]) => (
                    <div key={ch} className="border-t border-steel pt-3">
                      <p
                        className="font-mono text-[10px] tracking-[0.22em] uppercase mb-2"
                        style={{ color: c1 }}
                      >
                        {ch}
                      </p>
                      <p className="text-sm leading-snug text-ash">{idea}</p>
                    </div>
                  ))}
              </div>
            </motion.div>
          )}

        {/* ============ 18 / DETAILS BAR (closing summary) ============ */}
        <motion.div
          {...tileMotion(17)}
          className="rounded-lg p-6 flex flex-wrap items-center justify-between gap-y-4"
          style={{
            background: c0,
            color: c2,
            gridColumn: "span 12",
            gridRow: "span 1",
            minHeight: "120px",
          }}
        >
          <DetailBlock label="archetypes" value={archetypeLabel} color={c2} accent={c1} />
          <DetailBlock label="tone" value={toneLabel || "—"} color={c2} accent={c1} />
          <DetailBlock label="display type" value={displayFont} color={c2} accent={c1} />
          <DetailBlock label="body type" value={bodyFont} color={c2} accent={c1} />
          <DetailBlock label="palette" value={palette?.name ?? "—"} color={c2} accent={c1} />
          <DetailBlock label="surfaces" value="8 applied" color={c2} accent={c1} />
        </motion.div>
      </div>
    </>
  );
}

// ============================================================
// Sub-components
// ============================================================

function MockupTile({
  image,
  regenerating,
  onRegen,
}: {
  image?: string;
  regenerating?: boolean;
  onRegen?: () => void;
}) {
  return (
    <>
      {image ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={image}
          alt="Mockup"
          className="absolute inset-0 w-full h-full object-cover"
        />
      ) : (
        <div className="absolute inset-0 flex flex-col items-center justify-center font-mono text-xs text-ash gap-1">
          <span>generating…</span>
          <span className="text-[9px] tracking-widest uppercase opacity-60">Nano Banana 2</span>
        </div>
      )}
      {regenerating && (
        <div className="absolute inset-0 bg-noir/85 flex flex-col items-center justify-center z-10">
          <span className="font-mono text-[11px] tracking-widest uppercase text-spark animate-pulse mb-1">
            regenerating
          </span>
          <span className="font-mono text-[9px] tracking-widest uppercase text-ash">
            Nano Banana 2
          </span>
        </div>
      )}
      {onRegen && !regenerating && (
        <button
          type="button"
          onClick={onRegen}
          className="absolute bottom-3 right-3 opacity-0 group-hover:opacity-100 transition-opacity bg-noir/85 hover:bg-noir text-bone font-mono text-[10px] tracking-widest uppercase px-3 py-2 z-20 backdrop-blur rounded"
          aria-label="Regenerate this image"
        >
          ↻ regen
        </button>
      )}
    </>
  );
}

function LogoVariant({
  background,
  accent,
  logo,
  label,
  textColor,
  outline,
}: {
  background: string;
  accent: string;
  logo?: string;
  label: string;
  textColor?: string;
  outline?: boolean;
}) {
  return (
    <div
      className="flex flex-col p-3 rounded relative"
      style={{
        background,
        border: outline ? `1px dashed ${accent}80` : `1px solid #1f2128`,
      }}
    >
      <div className="flex-1 flex items-center justify-center min-h-0">
        {logo ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={logo}
            alt="Logo variant"
            className="max-w-[80%] max-h-full object-contain"
            style={
              outline
                ? { filter: "grayscale(1) invert(1) contrast(1.2)", opacity: 0.85 }
                : background === "transparent"
                ? { filter: "grayscale(1)" }
                : undefined
            }
          />
        ) : (
          <span className="font-mono text-[10px] tracking-widest uppercase" style={{ color: accent, opacity: 0.5 }}>
            no logo
          </span>
        )}
      </div>
      <p
        className="font-mono text-[9px] tracking-widest uppercase mt-2 text-center"
        style={{ color: textColor || (background === "transparent" ? "#6b6b73" : "#6b6b73") }}
      >
        {label}
      </p>
    </div>
  );
}

/**
 * Campaign-specific lockup: the campaign name set in the display font is the
 * campaign's "typography logo".
 */
function WordmarkVariant({
  background,
  textColor,
  accent,
  text,
  font,
  label,
  outline,
}: {
  background: string;
  textColor: string;
  accent: string;
  text: string;
  font: string;
  label: string;
  outline?: boolean;
}) {
  const len = (text || "").length;
  const size = len > 14 ? 18 : len > 9 ? 22 : 28;
  return (
    <div
      className="flex flex-col p-3 rounded relative"
      style={{
        background: background === "transparent" ? "#0a0a0a" : background,
        border: outline ? `1px dashed ${accent}80` : `1px solid #1f2128`,
      }}
    >
      <div className="flex-1 flex items-center justify-center min-h-0 overflow-hidden">
        <span
          className="leading-none tracking-tightest text-center"
          style={{
            fontFamily: `'${font}', serif`,
            color: textColor,
            fontSize: size,
            fontWeight: 700,
            letterSpacing: "-0.02em",
          }}
        >
          {text}
          <span style={{ color: accent }}>.</span>
        </span>
      </div>
      <p
        className="font-mono text-[9px] tracking-widest uppercase mt-2 text-center"
        style={{ color: outline ? "#6b6b73" : "#6b6b73" }}
      >
        {label}
      </p>
    </div>
  );
}

function ColorCell({ hex, role }: { hex: string; role: string }) {
  const text = contrast(hex);
  return (
    <div className="flex flex-col justify-between p-3" style={{ background: hex, color: text }}>
      <p className="font-mono text-[9px] tracking-widest uppercase opacity-70" style={{ color: text }}>
        {role}
      </p>
      <p className="font-mono text-[10px] tracking-widest uppercase" style={{ color: text }}>
        {hex.toUpperCase()}
      </p>
    </div>
  );
}

function DetailBlock({
  label,
  value,
  color,
  accent,
}: {
  label: string;
  value: string;
  color: string;
  accent: string;
}) {
  return (
    <div className="min-w-[120px] max-w-[200px]">
      <p className="font-mono text-[9px] tracking-[0.22em] uppercase mb-1" style={{ color: accent }}>
        {label}
      </p>
      <p className="text-sm leading-tight truncate" style={{ color, opacity: 0.92 }}>
        {value || "—"}
      </p>
    </div>
  );
}

// ---------- Principle icons (essence) ----------

function PrincipleIcon({ idx, color }: { idx: number; color: string }) {
  const sw = 1.8;
  if (idx === 0)
    return (
      <svg width="18" height="18" viewBox="0 0 24 24" fill={color} stroke={color} strokeWidth={sw} strokeLinejoin="round">
        <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
      </svg>
    );
  if (idx === 1)
    return (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={sw} strokeLinejoin="round">
        <rect x="4" y="4" width="16" height="16" rx="3" fill={color} fillOpacity="0.85" />
      </svg>
    );
  if (idx === 2)
    return (
      <svg width="18" height="18" viewBox="0 0 24 24" fill={color} stroke={color} strokeWidth={sw} strokeLinejoin="round">
        <path d="M12 2 C 14 7 19 11 19 16 a 7 7 0 0 1 -14 0 c 0 -5 5 -9 7 -14 z" />
      </svg>
    );
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill={color} stroke={color} strokeWidth={sw} strokeLinejoin="round">
      <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z" />
    </svg>
  );
}

// ---------- Contrast utility ----------

function contrast(hex: string): string {
  const c = (hex || "").replace("#", "");
  if (c.length !== 6) return "#f4f0e6";
  const r = parseInt(c.slice(0, 2), 16);
  const g = parseInt(c.slice(2, 4), 16);
  const b = parseInt(c.slice(4, 6), 16);
  const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return lum > 0.55 ? "#0a0a0a" : "#f4f0e6";
}
