"use client";
import type { ColorPalette } from "@/lib/types";

type Props = {
  options: ColorPalette[];
  selected?: ColorPalette;
  onSelect: (p: ColorPalette) => void;
  thumbnailsLoading?: boolean;
  onLoadMore?: () => void;
  loadingMore?: boolean;
};

export default function PalettePicker({
  options,
  selected,
  onSelect,
  thumbnailsLoading,
  onLoadMore,
  loadingMore,
}: Props) {
  return (
    <div>
      <div className="space-y-4">
        {options.map((p, idx) => (
          <PaletteCard
            key={`${p.name}-${idx}`}
            palette={p}
            index={idx}
            selected={selected?.name === p.name}
            thumbnailsLoading={thumbnailsLoading}
            onSelect={() => onSelect(p)}
          />
        ))}
      </div>

      {onLoadMore && (
        <div className="mt-6 flex items-center justify-center">
          <button
            onClick={onLoadMore}
            disabled={loadingMore}
            className="btn btn-ghost"
            aria-label="Generate more palette directions"
          >
            {loadingMore ? "Reasoning…" : `+ More directions`}
          </button>
        </div>
      )}

      <p className="mt-4 text-center font-mono text-[10px] tracking-[0.18em] uppercase text-ash">
        {options.length} direction{options.length === 1 ? "" : "s"} generated by Gemini
      </p>
    </div>
  );
}

function PaletteCard({
  palette: p,
  index,
  selected,
  thumbnailsLoading,
  onSelect,
}: {
  palette: ColorPalette;
  index: number;
  selected: boolean;
  thumbnailsLoading?: boolean;
  onSelect: () => void;
}) {
  const hasThumb = Boolean(p.conceptImageDataUrl);

  return (
    <button
      onClick={onSelect}
      className={`group w-full text-left border transition-all overflow-hidden flex flex-col md:flex-row ${
        selected ? "border-spark" : "border-steel hover:border-ash"
      }`}
    >
      {/* LEFT: visual concept + swatches */}
      <div className="md:w-[420px] md:flex-none flex-shrink-0 flex flex-col">
        {/* Concept thumbnail */}
        <div
          className="relative bg-carbon flex items-center justify-center"
          style={{ aspectRatio: "4 / 3" }}
        >
          {hasThumb ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={p.conceptImageDataUrl}
              alt={`Concept for ${p.name}`}
              className="absolute inset-0 w-full h-full object-cover"
            />
          ) : thumbnailsLoading ? (
            <div className="flex flex-col items-center gap-2 text-ash">
              <span className="font-mono text-[10px] tracking-widest uppercase animate-pulse">
                rendering…
              </span>
              <span className="font-mono text-[10px] text-ash/60">
                Nano Banana
              </span>
            </div>
          ) : (
            <span className="font-mono text-[10px] tracking-widest uppercase text-ash/60">
              preview unavailable
            </span>
          )}
          <span className="absolute top-3 left-3 font-mono text-[10px] tracking-[0.18em] uppercase text-bone/95 mix-blend-difference">
            Direction {String(index + 1).padStart(2, "0")}
          </span>
          {selected && (
            <span className="absolute top-3 right-3 font-mono text-[10px] tracking-[0.18em] uppercase text-spark">
              ● selected
            </span>
          )}
        </div>

        {/* Color stack */}
        <div className="flex h-16">
          {p.hexes.map((h) => (
            <div
              key={h}
              style={{ background: h }}
              className="flex-1 flex items-end justify-start p-2"
            >
              <span
                className="font-mono text-[9px] uppercase tracking-wider"
                style={{ color: contrastOn(h) }}
              >
                {h.replace("#", "")}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* RIGHT: description */}
      <div className="flex-1 p-6 md:p-8 flex flex-col justify-between">
        <div>
          <p className="eyebrow mb-3">— direction {String(index + 1).padStart(2, "0")}</p>
          <h3 className="display text-4xl md:text-5xl mb-4 leading-none">
            {p.name}.
          </h3>
          <p className="text-bone text-base md:text-lg leading-relaxed max-w-xl">
            {p.rationale}
          </p>
        </div>

        <div className="mt-6 flex flex-wrap gap-3 items-center">
          {p.hexes.map((h, i) => (
            <div key={h} className="flex items-center gap-2">
              <span
                className="w-4 h-4 border border-steel"
                style={{ background: h }}
              />
              <span className="font-mono text-[10px] tracking-widest uppercase text-ash">
                {tokenName(i)}
              </span>
            </div>
          ))}
        </div>

        {selected && (
          <p className="mt-5 font-mono text-[10px] uppercase tracking-[0.2em] text-spark">
            ● This direction is selected
          </p>
        )}
      </div>
    </button>
  );
}

function tokenName(i: number) {
  return ["base", "accent", "surface", "pop"][i] ?? `c${i + 1}`;
}

function contrastOn(hex: string): string {
  const c = hex.replace("#", "");
  if (c.length !== 6) return "#f4f0e6";
  const r = parseInt(c.slice(0, 2), 16);
  const g = parseInt(c.slice(2, 4), 16);
  const b = parseInt(c.slice(4, 6), 16);
  const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return lum > 0.55 ? "#1a1a1a" : "#f4f0e6";
}
