"use client";
import type {
  GeneratedBrand,
  GeneratedCampaign,
  ColorPalette,
  TypePairing,
} from "./types";
import { languageNative } from "./languages";
import { archetypeByKey } from "./archetypes";

/** Convert a data URL to a Blob */
function dataUrlToBlob(dataUrl: string): Blob {
  const [meta, b64] = dataUrl.split(",");
  const mime = /:([^;]+);/.exec(meta)?.[1] ?? "application/octet-stream";
  const bin = atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return new Blob([arr], { type: mime });
}

function inferExt(dataUrl: string): string {
  const m = /:([^;]+);/.exec(dataUrl);
  const mime = m?.[1] ?? "image/png";
  if (mime.includes("svg")) return "svg";
  if (mime.includes("jpeg") || mime.includes("jpg")) return "jpg";
  if (mime.includes("webp")) return "webp";
  return "png";
}

function safeName(s: string): string {
  return (s || "untitled")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9-_]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50);
}

function buildColorsCss(palette: ColorPalette): string {
  return `/* ${palette.name} — ${palette.rationale} */
:root {
${palette.hexes.map((h, i) => `  --brand-${i + 1}: ${h};`).join("\n")}
}

.brand-bg { background: var(--brand-1); color: var(--brand-3); }
.brand-accent { color: var(--brand-2); }
.brand-accent-bg { background: var(--brand-2); color: var(--brand-1); }
.brand-surface { background: var(--brand-3); color: var(--brand-1); }
.brand-pop { color: var(--brand-4); }
`;
}

function buildColorsJson(palette: ColorPalette) {
  return JSON.stringify(
    {
      name: palette.name,
      rationale: palette.rationale,
      tokens: {
        base: palette.hexes[0],
        accent: palette.hexes[1],
        surface: palette.hexes[2],
        pop: palette.hexes[3],
      },
      hexes: palette.hexes,
    },
    null,
    2
  );
}

function buildTypeReadme(t: TypePairing): string {
  return `# Typography

## Display — ${t.display}
Google Fonts: https://fonts.google.com/specimen/${t.display.replace(/\s+/g, "+")}

\`\`\`html
<link href="https://fonts.googleapis.com/css2?family=${t.display.replace(/\s+/g, "+")}:wght@400;500&display=swap" rel="stylesheet">
\`\`\`

## Body — ${t.body}
Google Fonts: https://fonts.google.com/specimen/${t.body.replace(/\s+/g, "+")}

\`\`\`html
<link href="https://fonts.googleapis.com/css2?family=${t.body.replace(/\s+/g, "+")}:wght@400;500&display=swap" rel="stylesheet">
\`\`\`

## CSS variables

\`\`\`css
--font-display: '${t.display}', serif;
--font-body: '${t.body}', sans-serif;
\`\`\`

## Why this pairing
${t.rationale}
`;
}

function buildBrandReadme(g: GeneratedBrand): string {
  const arch = g.input.archetypes
    .map((k) => archetypeByKey(k).name)
    .join(" + ");
  return `# ${g.input.businessName} — Brand Playbook

> ${g.tagline || "—"}

**Industry:** ${g.input.industry}
**Archetypes:** ${arch}
**Tone:** ${g.input.toneKeywords.join(", ")}
**Output language:** ${languageNative(g.input.outputLanguage)}

---

## What we do
${g.input.description}

## Who it's for
${g.input.targetAudience}

## Mission
${g.input.mission}

---

## Story
${g.story}

## Persona — ${g.persona.name}
${g.persona.description}

**Traits:** ${g.persona.traits.join(" · ")}

## Pattern
${g.patternIdea}

---

## Files in this pack
- \`playbook.pdf\` — printable brand book
- \`assets/logo.*\` — brand logo (raw)
- \`assets/mockup-*.*\` — applied visual mockups
- \`assets/colors.css\` — CSS variables ready to use
- \`assets/colors.json\` — palette as JSON tokens
- \`assets/type.md\` — typography reference
- \`brand.json\` — full data dump (use to re-import to BRND)

— Generated by BRND. Reasoned by Gemini · Rendered by Nano Banana 2.
`;
}

function buildCampaignReadme(g: GeneratedCampaign): string {
  const arch = g.input.archetypes
    .map((k) => archetypeByKey(k).name)
    .join(" + ");
  return `# ${g.input.campaignName} — Campaign Playbook
*for ${g.input.brandName}*

---

**Archetypes:** ${arch}
**Tone:** ${g.input.toneKeywords.join(", ")}
**Channels:** ${g.input.channels.join(" · ")}
**Output language:** ${languageNative(g.input.outputLanguage)}

---

## Brand
${g.input.brandDescription}

## Campaign purpose
${g.input.campaignPurpose}

## The story
${g.input.campaignStory}

## Target
${g.input.targetMarket}

---

## Voice — ${g.persona.name}
${g.persona.description}

**Traits:** ${g.persona.traits.join(" · ")}

---

## Headlines
${g.headlines.map((h) => `- ${h}`).join("\n")}

## CTA
**${g.cta}**

---

## Channel ideas
${Object.entries(g.channelIdeas)
  .filter(([, v]) => v && v.length > 0)
  .map(([ch, idea]) => `### ${ch.toUpperCase()}\n${idea}`)
  .join("\n\n")}

---

## Files in this pack
- \`playbook.pdf\` — printable campaign book
- \`assets/logo.*\` — your brand logo (as uploaded)
- \`assets/visual-*.*\` — generated campaign visuals
- \`assets/colors.css\` — CSS variables ready to use
- \`assets/colors.json\` — palette as JSON tokens
- \`assets/type.md\` — typography reference
- \`campaign.json\` — full data dump

— Generated by BRND. Reasoned by Gemini · Rendered by Nano Banana 2.
`;
}

async function pdfBlob(node: React.ReactElement): Promise<Blob> {
  const { pdf } = await import("@react-pdf/renderer");
  return await pdf(node).toBlob();
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function downloadBrandPlaybook(g: GeneratedBrand) {
  const JSZip = (await import("jszip")).default;
  const { buildBrandPlaybook } = await import("@/components/PlaybookPDF");

  const zip = new JSZip();
  const base = safeName(g.input.businessName) || "brand";

  // README
  zip.file("README.md", buildBrandReadme(g));

  // PDF
  const pdfNode = buildBrandPlaybook(g, languageNative(g.input.outputLanguage));
  const blob = await pdfBlob(pdfNode);
  zip.file(`${base}-playbook.pdf`, blob);

  // Assets folder
  const assets = zip.folder("assets")!;

  // Logo
  if (g.logoImageDataUrl) {
    assets.file(`logo.${inferExt(g.logoImageDataUrl)}`, dataUrlToBlob(g.logoImageDataUrl));
  }

  // Mockups
  g.mockupImages.forEach((img, i) => {
    if (img) {
      assets.file(
        `mockup-${String(i + 1).padStart(2, "0")}.${inferExt(img)}`,
        dataUrlToBlob(img)
      );
    }
  });

  // Concept thumbnails (the directions that were considered)
  g.palettes.forEach((p, i) => {
    if (p.conceptImageDataUrl) {
      assets.file(
        `concept-${String(i + 1).padStart(2, "0")}-${safeName(p.name)}.${inferExt(p.conceptImageDataUrl)}`,
        dataUrlToBlob(p.conceptImageDataUrl)
      );
    }
  });

  // Color tokens
  assets.file("colors.css", buildColorsCss(g.selectedPalette));
  assets.file("colors.json", buildColorsJson(g.selectedPalette));

  // Type
  assets.file("type.md", buildTypeReadme(g.selectedType));

  // Data dump (for re-import)
  zip.file("brand.json", JSON.stringify(g, null, 2));

  const out = await zip.generateAsync({ type: "blob" });
  triggerDownload(out, `${base}-playbook.zip`);
}

export async function downloadCampaignPlaybook(g: GeneratedCampaign) {
  const JSZip = (await import("jszip")).default;
  const { buildCampaignPlaybook } = await import("@/components/PlaybookPDF");

  const zip = new JSZip();
  const base = safeName(
    `${g.input.brandName}-${g.input.campaignName}`
  ) || "campaign";

  zip.file("README.md", buildCampaignReadme(g));

  const pdfNode = buildCampaignPlaybook(g, languageNative(g.input.outputLanguage));
  const blob = await pdfBlob(pdfNode);
  zip.file(`${base}-playbook.pdf`, blob);

  const assets = zip.folder("assets")!;

  if (g.input.logoDataUrl) {
    assets.file(`logo.${inferExt(g.input.logoDataUrl)}`, dataUrlToBlob(g.input.logoDataUrl));
  }

  g.mockupImages.forEach((img, i) => {
    if (img) {
      assets.file(
        `visual-${String(i + 1).padStart(2, "0")}.${inferExt(img)}`,
        dataUrlToBlob(img)
      );
    }
  });

  g.palettes.forEach((p, i) => {
    if (p.conceptImageDataUrl) {
      assets.file(
        `concept-${String(i + 1).padStart(2, "0")}-${safeName(p.name)}.${inferExt(p.conceptImageDataUrl)}`,
        dataUrlToBlob(p.conceptImageDataUrl)
      );
    }
  });

  assets.file("colors.css", buildColorsCss(g.selectedPalette));
  assets.file("colors.json", buildColorsJson(g.selectedPalette));
  assets.file("type.md", buildTypeReadme(g.selectedType));

  zip.file("campaign.json", JSON.stringify(g, null, 2));

  const out = await zip.generateAsync({ type: "blob" });
  triggerDownload(out, `${base}-playbook.zip`);
}
